frameworks:
    credence:
        kld_rigidity_range: [0.08,0.08]
        max_epochs: 1000
        lr: 0.00001
        merge_plots: True
        latent_dim: 9
        hidden_dims: [8,16,32,16,8]
        output_dir_name: 'credence'
        use_uniform_autoencoder: False
    modified_credence:
        kld_rigidity_range: [0.1,0.15]
        max_epochs: 1000
        lr: 0.00001
        merge_plots: False
        latent_dim: 9
        hidden_dims: [8,16,32,16,8]
        output_dir_name: 'modified-credence'
        use_uniform_autoencoder: False
dataset_type: 'acic19_linear'